name: Invite me to the Keymeta Networks
description: I would like to be part of the awesome community
title: "Please invite me to the Keymeta Networks"
labels: [github-invitation]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true
  - type: input
    id: discordname
    attributes:
      label: E-mail address
      placeholder: Insert your e-mail here
    validations:
      required: false
  - type: textarea
    id: Additional
    attributes:
      label: Additional Context
      description: Where did you meet Keymeta Networks? What do you like about this community? Why do you want to join?
    validations:
      required: true
