on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite-on-label
        uses: vj-abigo/invite-on-label@v1.2
        with:
          organization: keymeta-networks
          label: github-invitation
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: "![image](https://avatars.githubusercontent.com/u/99186009?s=200&v=4)<br><b>Invitation sent to join the GitHub Organization. Welcome to Keymeta Networks 🎉</b><br><br>Please check your mail to accept the invitation sent by the bot! 🤖<br><h1>About us</h1> Keymeta is a base of developers in various specialties that are interconnected with each other like a network."
        env:
          INVITE_TOKEN: ${{ secrets.DEV_INVITE_TOKEN }}
